import { UpsertPlatformOwnerData, UpsertPlatformOwnerVariables, CreateClientData, CreateClientVariables, UpdateClientData, UpdateClientVariables, CreateClientAiBotConfigData, CreateClientAiBotConfigVariables, UpdateClientAiBotConfigData, UpdateClientAiBotConfigVariables, CreateClientInboundContactData, CreateClientInboundContactVariables, UpdateClientInboundContactData, UpdateClientInboundContactVariables, CreatePlatformInboundContactData, CreatePlatformInboundContactVariables, CreatePlatformOutboundContactData, CreatePlatformOutboundContactVariables, CreatePlatformOutboundOutreachEventData, CreatePlatformOutboundOutreachEventVariables, CreatePlatformAgentActivityData, CreatePlatformAgentActivityVariables, CreateClientAiBotPerformanceEventData, CreateClientAiBotPerformanceEventVariables, CreateClientConversationData, CreateClientConversationVariables, UpdateClientConversationData, UpdateClientConversationVariables, CreateClientAdminData, CreateClientAdminVariables, UpdateClientAdminData, UpdateClientAdminVariables, WebhookCreateClientWithConfigData, WebhookCreateClientWithConfigVariables, CreateClientAiBotConfigAdminData, CreateClientAiBotConfigAdminVariables, UpdateClientAiBotConfigAdminData, UpdateClientAiBotConfigAdminVariables, GetClientByLinkedAuthUidData, GetClientByLinkedAuthUidVariables, GetClientByIdData, GetClientByIdVariables, GetClientAiBotConfigByAccessTokenData, GetClientAiBotConfigByAccessTokenVariables, ListClientInboundContactsByClientData, ListClientInboundContactsByClientVariables, ListClientsData, ListPlatformInboundContactsData, ListPlatformOutboundContactsData, ListPlatformOutboundOutreachEventsData, ListPlatformAgentActivitiesData, ListClientAiBotPerformanceEventsData, ListClientAiBotPerformanceEventsVariables, GetClientConversationData, GetClientConversationVariables, ListClientConversationsByClientAndTokenData, ListClientConversationsByClientAndTokenVariables, ListClientConversationsByAccessTokenData, ListClientConversationsByAccessTokenVariables, GetClientByLinkedAuthUidAdminData, GetClientByLinkedAuthUidAdminVariables, GetClientByPaddleSubscriptionIdAdminData, GetClientByPaddleSubscriptionIdAdminVariables } from '../';
import { UseDataConnectQueryResult, useDataConnectQueryOptions, UseDataConnectMutationResult, useDataConnectMutationOptions} from '@tanstack-query-firebase/react/data-connect';
import { UseQueryResult, UseMutationResult} from '@tanstack/react-query';
import { DataConnect } from 'firebase/data-connect';
import { FirebaseError } from 'firebase/app';


export function useUpsertPlatformOwner(options?: useDataConnectMutationOptions<UpsertPlatformOwnerData, FirebaseError, UpsertPlatformOwnerVariables | void>): UseDataConnectMutationResult<UpsertPlatformOwnerData, UpsertPlatformOwnerVariables>;
export function useUpsertPlatformOwner(dc: DataConnect, options?: useDataConnectMutationOptions<UpsertPlatformOwnerData, FirebaseError, UpsertPlatformOwnerVariables | void>): UseDataConnectMutationResult<UpsertPlatformOwnerData, UpsertPlatformOwnerVariables>;

export function useCreateClient(options?: useDataConnectMutationOptions<CreateClientData, FirebaseError, CreateClientVariables | void>): UseDataConnectMutationResult<CreateClientData, CreateClientVariables>;
export function useCreateClient(dc: DataConnect, options?: useDataConnectMutationOptions<CreateClientData, FirebaseError, CreateClientVariables | void>): UseDataConnectMutationResult<CreateClientData, CreateClientVariables>;

export function useUpdateClient(options?: useDataConnectMutationOptions<UpdateClientData, FirebaseError, UpdateClientVariables>): UseDataConnectMutationResult<UpdateClientData, UpdateClientVariables>;
export function useUpdateClient(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateClientData, FirebaseError, UpdateClientVariables>): UseDataConnectMutationResult<UpdateClientData, UpdateClientVariables>;

export function useCreateClientAiBotConfig(options?: useDataConnectMutationOptions<CreateClientAiBotConfigData, FirebaseError, CreateClientAiBotConfigVariables>): UseDataConnectMutationResult<CreateClientAiBotConfigData, CreateClientAiBotConfigVariables>;
export function useCreateClientAiBotConfig(dc: DataConnect, options?: useDataConnectMutationOptions<CreateClientAiBotConfigData, FirebaseError, CreateClientAiBotConfigVariables>): UseDataConnectMutationResult<CreateClientAiBotConfigData, CreateClientAiBotConfigVariables>;

export function useUpdateClientAiBotConfig(options?: useDataConnectMutationOptions<UpdateClientAiBotConfigData, FirebaseError, UpdateClientAiBotConfigVariables>): UseDataConnectMutationResult<UpdateClientAiBotConfigData, UpdateClientAiBotConfigVariables>;
export function useUpdateClientAiBotConfig(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateClientAiBotConfigData, FirebaseError, UpdateClientAiBotConfigVariables>): UseDataConnectMutationResult<UpdateClientAiBotConfigData, UpdateClientAiBotConfigVariables>;

export function useCreateClientInboundContact(options?: useDataConnectMutationOptions<CreateClientInboundContactData, FirebaseError, CreateClientInboundContactVariables>): UseDataConnectMutationResult<CreateClientInboundContactData, CreateClientInboundContactVariables>;
export function useCreateClientInboundContact(dc: DataConnect, options?: useDataConnectMutationOptions<CreateClientInboundContactData, FirebaseError, CreateClientInboundContactVariables>): UseDataConnectMutationResult<CreateClientInboundContactData, CreateClientInboundContactVariables>;

export function useUpdateClientInboundContact(options?: useDataConnectMutationOptions<UpdateClientInboundContactData, FirebaseError, UpdateClientInboundContactVariables>): UseDataConnectMutationResult<UpdateClientInboundContactData, UpdateClientInboundContactVariables>;
export function useUpdateClientInboundContact(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateClientInboundContactData, FirebaseError, UpdateClientInboundContactVariables>): UseDataConnectMutationResult<UpdateClientInboundContactData, UpdateClientInboundContactVariables>;

export function useCreatePlatformInboundContact(options?: useDataConnectMutationOptions<CreatePlatformInboundContactData, FirebaseError, CreatePlatformInboundContactVariables | void>): UseDataConnectMutationResult<CreatePlatformInboundContactData, CreatePlatformInboundContactVariables>;
export function useCreatePlatformInboundContact(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePlatformInboundContactData, FirebaseError, CreatePlatformInboundContactVariables | void>): UseDataConnectMutationResult<CreatePlatformInboundContactData, CreatePlatformInboundContactVariables>;

export function useCreatePlatformOutboundContact(options?: useDataConnectMutationOptions<CreatePlatformOutboundContactData, FirebaseError, CreatePlatformOutboundContactVariables | void>): UseDataConnectMutationResult<CreatePlatformOutboundContactData, CreatePlatformOutboundContactVariables>;
export function useCreatePlatformOutboundContact(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePlatformOutboundContactData, FirebaseError, CreatePlatformOutboundContactVariables | void>): UseDataConnectMutationResult<CreatePlatformOutboundContactData, CreatePlatformOutboundContactVariables>;

export function useCreatePlatformOutboundOutreachEvent(options?: useDataConnectMutationOptions<CreatePlatformOutboundOutreachEventData, FirebaseError, CreatePlatformOutboundOutreachEventVariables>): UseDataConnectMutationResult<CreatePlatformOutboundOutreachEventData, CreatePlatformOutboundOutreachEventVariables>;
export function useCreatePlatformOutboundOutreachEvent(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePlatformOutboundOutreachEventData, FirebaseError, CreatePlatformOutboundOutreachEventVariables>): UseDataConnectMutationResult<CreatePlatformOutboundOutreachEventData, CreatePlatformOutboundOutreachEventVariables>;

export function useCreatePlatformAgentActivity(options?: useDataConnectMutationOptions<CreatePlatformAgentActivityData, FirebaseError, CreatePlatformAgentActivityVariables | void>): UseDataConnectMutationResult<CreatePlatformAgentActivityData, CreatePlatformAgentActivityVariables>;
export function useCreatePlatformAgentActivity(dc: DataConnect, options?: useDataConnectMutationOptions<CreatePlatformAgentActivityData, FirebaseError, CreatePlatformAgentActivityVariables | void>): UseDataConnectMutationResult<CreatePlatformAgentActivityData, CreatePlatformAgentActivityVariables>;

export function useCreateClientAiBotPerformanceEvent(options?: useDataConnectMutationOptions<CreateClientAiBotPerformanceEventData, FirebaseError, CreateClientAiBotPerformanceEventVariables>): UseDataConnectMutationResult<CreateClientAiBotPerformanceEventData, CreateClientAiBotPerformanceEventVariables>;
export function useCreateClientAiBotPerformanceEvent(dc: DataConnect, options?: useDataConnectMutationOptions<CreateClientAiBotPerformanceEventData, FirebaseError, CreateClientAiBotPerformanceEventVariables>): UseDataConnectMutationResult<CreateClientAiBotPerformanceEventData, CreateClientAiBotPerformanceEventVariables>;

export function useCreateClientConversation(options?: useDataConnectMutationOptions<CreateClientConversationData, FirebaseError, CreateClientConversationVariables>): UseDataConnectMutationResult<CreateClientConversationData, CreateClientConversationVariables>;
export function useCreateClientConversation(dc: DataConnect, options?: useDataConnectMutationOptions<CreateClientConversationData, FirebaseError, CreateClientConversationVariables>): UseDataConnectMutationResult<CreateClientConversationData, CreateClientConversationVariables>;

export function useUpdateClientConversation(options?: useDataConnectMutationOptions<UpdateClientConversationData, FirebaseError, UpdateClientConversationVariables>): UseDataConnectMutationResult<UpdateClientConversationData, UpdateClientConversationVariables>;
export function useUpdateClientConversation(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateClientConversationData, FirebaseError, UpdateClientConversationVariables>): UseDataConnectMutationResult<UpdateClientConversationData, UpdateClientConversationVariables>;

export function useCreateClientAdmin(options?: useDataConnectMutationOptions<CreateClientAdminData, FirebaseError, CreateClientAdminVariables>): UseDataConnectMutationResult<CreateClientAdminData, CreateClientAdminVariables>;
export function useCreateClientAdmin(dc: DataConnect, options?: useDataConnectMutationOptions<CreateClientAdminData, FirebaseError, CreateClientAdminVariables>): UseDataConnectMutationResult<CreateClientAdminData, CreateClientAdminVariables>;

export function useUpdateClientAdmin(options?: useDataConnectMutationOptions<UpdateClientAdminData, FirebaseError, UpdateClientAdminVariables>): UseDataConnectMutationResult<UpdateClientAdminData, UpdateClientAdminVariables>;
export function useUpdateClientAdmin(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateClientAdminData, FirebaseError, UpdateClientAdminVariables>): UseDataConnectMutationResult<UpdateClientAdminData, UpdateClientAdminVariables>;

export function useWebhookCreateClientWithConfig(options?: useDataConnectMutationOptions<WebhookCreateClientWithConfigData, FirebaseError, WebhookCreateClientWithConfigVariables>): UseDataConnectMutationResult<WebhookCreateClientWithConfigData, WebhookCreateClientWithConfigVariables>;
export function useWebhookCreateClientWithConfig(dc: DataConnect, options?: useDataConnectMutationOptions<WebhookCreateClientWithConfigData, FirebaseError, WebhookCreateClientWithConfigVariables>): UseDataConnectMutationResult<WebhookCreateClientWithConfigData, WebhookCreateClientWithConfigVariables>;

export function useCreateClientAiBotConfigAdmin(options?: useDataConnectMutationOptions<CreateClientAiBotConfigAdminData, FirebaseError, CreateClientAiBotConfigAdminVariables>): UseDataConnectMutationResult<CreateClientAiBotConfigAdminData, CreateClientAiBotConfigAdminVariables>;
export function useCreateClientAiBotConfigAdmin(dc: DataConnect, options?: useDataConnectMutationOptions<CreateClientAiBotConfigAdminData, FirebaseError, CreateClientAiBotConfigAdminVariables>): UseDataConnectMutationResult<CreateClientAiBotConfigAdminData, CreateClientAiBotConfigAdminVariables>;

export function useUpdateClientAiBotConfigAdmin(options?: useDataConnectMutationOptions<UpdateClientAiBotConfigAdminData, FirebaseError, UpdateClientAiBotConfigAdminVariables>): UseDataConnectMutationResult<UpdateClientAiBotConfigAdminData, UpdateClientAiBotConfigAdminVariables>;
export function useUpdateClientAiBotConfigAdmin(dc: DataConnect, options?: useDataConnectMutationOptions<UpdateClientAiBotConfigAdminData, FirebaseError, UpdateClientAiBotConfigAdminVariables>): UseDataConnectMutationResult<UpdateClientAiBotConfigAdminData, UpdateClientAiBotConfigAdminVariables>;

export function useGetClientByLinkedAuthUid(vars: GetClientByLinkedAuthUidVariables, options?: useDataConnectQueryOptions<GetClientByLinkedAuthUidData>): UseDataConnectQueryResult<GetClientByLinkedAuthUidData, GetClientByLinkedAuthUidVariables>;
export function useGetClientByLinkedAuthUid(dc: DataConnect, vars: GetClientByLinkedAuthUidVariables, options?: useDataConnectQueryOptions<GetClientByLinkedAuthUidData>): UseDataConnectQueryResult<GetClientByLinkedAuthUidData, GetClientByLinkedAuthUidVariables>;

export function useGetClientById(vars: GetClientByIdVariables, options?: useDataConnectQueryOptions<GetClientByIdData>): UseDataConnectQueryResult<GetClientByIdData, GetClientByIdVariables>;
export function useGetClientById(dc: DataConnect, vars: GetClientByIdVariables, options?: useDataConnectQueryOptions<GetClientByIdData>): UseDataConnectQueryResult<GetClientByIdData, GetClientByIdVariables>;

export function useGetClientAiBotConfigByAccessToken(vars: GetClientAiBotConfigByAccessTokenVariables, options?: useDataConnectQueryOptions<GetClientAiBotConfigByAccessTokenData>): UseDataConnectQueryResult<GetClientAiBotConfigByAccessTokenData, GetClientAiBotConfigByAccessTokenVariables>;
export function useGetClientAiBotConfigByAccessToken(dc: DataConnect, vars: GetClientAiBotConfigByAccessTokenVariables, options?: useDataConnectQueryOptions<GetClientAiBotConfigByAccessTokenData>): UseDataConnectQueryResult<GetClientAiBotConfigByAccessTokenData, GetClientAiBotConfigByAccessTokenVariables>;

export function useListClientInboundContactsByClient(vars: ListClientInboundContactsByClientVariables, options?: useDataConnectQueryOptions<ListClientInboundContactsByClientData>): UseDataConnectQueryResult<ListClientInboundContactsByClientData, ListClientInboundContactsByClientVariables>;
export function useListClientInboundContactsByClient(dc: DataConnect, vars: ListClientInboundContactsByClientVariables, options?: useDataConnectQueryOptions<ListClientInboundContactsByClientData>): UseDataConnectQueryResult<ListClientInboundContactsByClientData, ListClientInboundContactsByClientVariables>;

export function useListClients(options?: useDataConnectQueryOptions<ListClientsData>): UseDataConnectQueryResult<ListClientsData, undefined>;
export function useListClients(dc: DataConnect, options?: useDataConnectQueryOptions<ListClientsData>): UseDataConnectQueryResult<ListClientsData, undefined>;

export function useListPlatformInboundContacts(options?: useDataConnectQueryOptions<ListPlatformInboundContactsData>): UseDataConnectQueryResult<ListPlatformInboundContactsData, undefined>;
export function useListPlatformInboundContacts(dc: DataConnect, options?: useDataConnectQueryOptions<ListPlatformInboundContactsData>): UseDataConnectQueryResult<ListPlatformInboundContactsData, undefined>;

export function useListPlatformOutboundContacts(options?: useDataConnectQueryOptions<ListPlatformOutboundContactsData>): UseDataConnectQueryResult<ListPlatformOutboundContactsData, undefined>;
export function useListPlatformOutboundContacts(dc: DataConnect, options?: useDataConnectQueryOptions<ListPlatformOutboundContactsData>): UseDataConnectQueryResult<ListPlatformOutboundContactsData, undefined>;

export function useListPlatformOutboundOutreachEvents(options?: useDataConnectQueryOptions<ListPlatformOutboundOutreachEventsData>): UseDataConnectQueryResult<ListPlatformOutboundOutreachEventsData, undefined>;
export function useListPlatformOutboundOutreachEvents(dc: DataConnect, options?: useDataConnectQueryOptions<ListPlatformOutboundOutreachEventsData>): UseDataConnectQueryResult<ListPlatformOutboundOutreachEventsData, undefined>;

export function useListPlatformAgentActivities(options?: useDataConnectQueryOptions<ListPlatformAgentActivitiesData>): UseDataConnectQueryResult<ListPlatformAgentActivitiesData, undefined>;
export function useListPlatformAgentActivities(dc: DataConnect, options?: useDataConnectQueryOptions<ListPlatformAgentActivitiesData>): UseDataConnectQueryResult<ListPlatformAgentActivitiesData, undefined>;

export function useListClientAiBotPerformanceEvents(vars: ListClientAiBotPerformanceEventsVariables, options?: useDataConnectQueryOptions<ListClientAiBotPerformanceEventsData>): UseDataConnectQueryResult<ListClientAiBotPerformanceEventsData, ListClientAiBotPerformanceEventsVariables>;
export function useListClientAiBotPerformanceEvents(dc: DataConnect, vars: ListClientAiBotPerformanceEventsVariables, options?: useDataConnectQueryOptions<ListClientAiBotPerformanceEventsData>): UseDataConnectQueryResult<ListClientAiBotPerformanceEventsData, ListClientAiBotPerformanceEventsVariables>;

export function useGetClientConversation(vars: GetClientConversationVariables, options?: useDataConnectQueryOptions<GetClientConversationData>): UseDataConnectQueryResult<GetClientConversationData, GetClientConversationVariables>;
export function useGetClientConversation(dc: DataConnect, vars: GetClientConversationVariables, options?: useDataConnectQueryOptions<GetClientConversationData>): UseDataConnectQueryResult<GetClientConversationData, GetClientConversationVariables>;

export function useListClientConversationsByClientAndToken(vars: ListClientConversationsByClientAndTokenVariables, options?: useDataConnectQueryOptions<ListClientConversationsByClientAndTokenData>): UseDataConnectQueryResult<ListClientConversationsByClientAndTokenData, ListClientConversationsByClientAndTokenVariables>;
export function useListClientConversationsByClientAndToken(dc: DataConnect, vars: ListClientConversationsByClientAndTokenVariables, options?: useDataConnectQueryOptions<ListClientConversationsByClientAndTokenData>): UseDataConnectQueryResult<ListClientConversationsByClientAndTokenData, ListClientConversationsByClientAndTokenVariables>;

export function useListClientConversationsByAccessToken(vars: ListClientConversationsByAccessTokenVariables, options?: useDataConnectQueryOptions<ListClientConversationsByAccessTokenData>): UseDataConnectQueryResult<ListClientConversationsByAccessTokenData, ListClientConversationsByAccessTokenVariables>;
export function useListClientConversationsByAccessToken(dc: DataConnect, vars: ListClientConversationsByAccessTokenVariables, options?: useDataConnectQueryOptions<ListClientConversationsByAccessTokenData>): UseDataConnectQueryResult<ListClientConversationsByAccessTokenData, ListClientConversationsByAccessTokenVariables>;

export function useGetClientByLinkedAuthUidAdmin(vars: GetClientByLinkedAuthUidAdminVariables, options?: useDataConnectQueryOptions<GetClientByLinkedAuthUidAdminData>): UseDataConnectQueryResult<GetClientByLinkedAuthUidAdminData, GetClientByLinkedAuthUidAdminVariables>;
export function useGetClientByLinkedAuthUidAdmin(dc: DataConnect, vars: GetClientByLinkedAuthUidAdminVariables, options?: useDataConnectQueryOptions<GetClientByLinkedAuthUidAdminData>): UseDataConnectQueryResult<GetClientByLinkedAuthUidAdminData, GetClientByLinkedAuthUidAdminVariables>;

export function useGetClientByPaddleSubscriptionIdAdmin(vars: GetClientByPaddleSubscriptionIdAdminVariables, options?: useDataConnectQueryOptions<GetClientByPaddleSubscriptionIdAdminData>): UseDataConnectQueryResult<GetClientByPaddleSubscriptionIdAdminData, GetClientByPaddleSubscriptionIdAdminVariables>;
export function useGetClientByPaddleSubscriptionIdAdmin(dc: DataConnect, vars: GetClientByPaddleSubscriptionIdAdminVariables, options?: useDataConnectQueryOptions<GetClientByPaddleSubscriptionIdAdminData>): UseDataConnectQueryResult<GetClientByPaddleSubscriptionIdAdminData, GetClientByPaddleSubscriptionIdAdminVariables>;
