extend type Mutation {
  """
  ✨ Insert a single `Client` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  client_insert(
    """
    Data object to insert into the table.
    """
    data: Client_Data!
  ): Client_KeyOutput! @fdc_generated(from: "Client", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ClientAiBotConfig` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  clientAiBotConfig_insert(
    """
    Data object to insert into the table.
    """
    data: ClientAiBotConfig_Data!
  ): ClientAiBotConfig_KeyOutput! @fdc_generated(from: "ClientAiBotConfig", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ClientAiBotPerformanceEvent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  clientAiBotPerformanceEvent_insert(
    """
    Data object to insert into the table.
    """
    data: ClientAiBotPerformanceEvent_Data!
  ): ClientAiBotPerformanceEvent_KeyOutput! @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ClientConversation` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  clientConversation_insert(
    """
    Data object to insert into the table.
    """
    data: ClientConversation_Data!
  ): ClientConversation_KeyOutput! @fdc_generated(from: "ClientConversation", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ClientInboundContact` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  clientInboundContact_insert(
    """
    Data object to insert into the table.
    """
    data: ClientInboundContact_Data!
  ): ClientInboundContact_KeyOutput! @fdc_generated(from: "ClientInboundContact", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PlatformAgentActivity` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformAgentActivity_insert(
    """
    Data object to insert into the table.
    """
    data: PlatformAgentActivity_Data!
  ): PlatformAgentActivity_KeyOutput! @fdc_generated(from: "PlatformAgentActivity", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PlatformChatbotConfig` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformChatbotConfig_insert(
    """
    Data object to insert into the table.
    """
    data: PlatformChatbotConfig_Data!
  ): PlatformChatbotConfig_KeyOutput! @fdc_generated(from: "PlatformChatbotConfig", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PlatformInboundContact` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformInboundContact_insert(
    """
    Data object to insert into the table.
    """
    data: PlatformInboundContact_Data!
  ): PlatformInboundContact_KeyOutput! @fdc_generated(from: "PlatformInboundContact", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PlatformOutboundContact` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformOutboundContact_insert(
    """
    Data object to insert into the table.
    """
    data: PlatformOutboundContact_Data!
  ): PlatformOutboundContact_KeyOutput! @fdc_generated(from: "PlatformOutboundContact", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PlatformOutboundOutreachEvent` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformOutboundOutreachEvent_insert(
    """
    Data object to insert into the table.
    """
    data: PlatformOutboundOutreachEvent_Data!
  ): PlatformOutboundOutreachEvent_KeyOutput! @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PlatformOwner` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformOwner_insert(
    """
    Data object to insert into the table.
    """
    data: PlatformOwner_Data!
  ): PlatformOwner_KeyOutput! @fdc_generated(from: "PlatformOwner", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Client` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  client_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Client_Data!]!
  ): [Client_KeyOutput!]! @fdc_generated(from: "Client", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ClientAiBotConfig` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  clientAiBotConfig_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ClientAiBotConfig_Data!]!
  ): [ClientAiBotConfig_KeyOutput!]! @fdc_generated(from: "ClientAiBotConfig", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ClientAiBotPerformanceEvent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  clientAiBotPerformanceEvent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ClientAiBotPerformanceEvent_Data!]!
  ): [ClientAiBotPerformanceEvent_KeyOutput!]! @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ClientConversation` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  clientConversation_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ClientConversation_Data!]!
  ): [ClientConversation_KeyOutput!]! @fdc_generated(from: "ClientConversation", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ClientInboundContact` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  clientInboundContact_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ClientInboundContact_Data!]!
  ): [ClientInboundContact_KeyOutput!]! @fdc_generated(from: "ClientInboundContact", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PlatformAgentActivity` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformAgentActivity_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PlatformAgentActivity_Data!]!
  ): [PlatformAgentActivity_KeyOutput!]! @fdc_generated(from: "PlatformAgentActivity", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PlatformChatbotConfig` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformChatbotConfig_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PlatformChatbotConfig_Data!]!
  ): [PlatformChatbotConfig_KeyOutput!]! @fdc_generated(from: "PlatformChatbotConfig", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PlatformInboundContact` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformInboundContact_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PlatformInboundContact_Data!]!
  ): [PlatformInboundContact_KeyOutput!]! @fdc_generated(from: "PlatformInboundContact", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PlatformOutboundContact` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformOutboundContact_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PlatformOutboundContact_Data!]!
  ): [PlatformOutboundContact_KeyOutput!]! @fdc_generated(from: "PlatformOutboundContact", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PlatformOutboundOutreachEvent` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformOutboundOutreachEvent_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PlatformOutboundOutreachEvent_Data!]!
  ): [PlatformOutboundOutreachEvent_KeyOutput!]! @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PlatformOwner` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  platformOwner_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PlatformOwner_Data!]!
  ): [PlatformOwner_KeyOutput!]! @fdc_generated(from: "PlatformOwner", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Client` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Client`.
  """
  client_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Client_Data!
  ): Client_KeyOutput! @fdc_generated(from: "Client", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ClientAiBotConfig` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ClientAiBotConfig`.
  """
  clientAiBotConfig_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ClientAiBotConfig_Data!
  ): ClientAiBotConfig_KeyOutput! @fdc_generated(from: "ClientAiBotConfig", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ClientAiBotPerformanceEvent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ClientAiBotPerformanceEvent`.
  """
  clientAiBotPerformanceEvent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ClientAiBotPerformanceEvent_Data!
  ): ClientAiBotPerformanceEvent_KeyOutput! @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ClientConversation` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ClientConversation`.
  """
  clientConversation_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ClientConversation_Data!
  ): ClientConversation_KeyOutput! @fdc_generated(from: "ClientConversation", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ClientInboundContact` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ClientInboundContact`.
  """
  clientInboundContact_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ClientInboundContact_Data!
  ): ClientInboundContact_KeyOutput! @fdc_generated(from: "ClientInboundContact", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PlatformAgentActivity` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformAgentActivity`.
  """
  platformAgentActivity_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PlatformAgentActivity_Data!
  ): PlatformAgentActivity_KeyOutput! @fdc_generated(from: "PlatformAgentActivity", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PlatformChatbotConfig` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformChatbotConfig`.
  """
  platformChatbotConfig_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PlatformChatbotConfig_Data!
  ): PlatformChatbotConfig_KeyOutput! @fdc_generated(from: "PlatformChatbotConfig", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PlatformInboundContact` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformInboundContact`.
  """
  platformInboundContact_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PlatformInboundContact_Data!
  ): PlatformInboundContact_KeyOutput! @fdc_generated(from: "PlatformInboundContact", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PlatformOutboundContact` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformOutboundContact`.
  """
  platformOutboundContact_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PlatformOutboundContact_Data!
  ): PlatformOutboundContact_KeyOutput! @fdc_generated(from: "PlatformOutboundContact", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PlatformOutboundOutreachEvent` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformOutboundOutreachEvent`.
  """
  platformOutboundOutreachEvent_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PlatformOutboundOutreachEvent_Data!
  ): PlatformOutboundOutreachEvent_KeyOutput! @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PlatformOwner` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformOwner`.
  """
  platformOwner_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PlatformOwner_Data!
  ): PlatformOwner_KeyOutput! @fdc_generated(from: "PlatformOwner", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Client` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Client`.
  """
  client_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Client_Data!]!
  ): [Client_KeyOutput!]! @fdc_generated(from: "Client", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ClientAiBotConfig` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ClientAiBotConfig`.
  """
  clientAiBotConfig_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ClientAiBotConfig_Data!]!
  ): [ClientAiBotConfig_KeyOutput!]! @fdc_generated(from: "ClientAiBotConfig", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ClientAiBotPerformanceEvent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ClientAiBotPerformanceEvent`.
  """
  clientAiBotPerformanceEvent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ClientAiBotPerformanceEvent_Data!]!
  ): [ClientAiBotPerformanceEvent_KeyOutput!]! @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ClientConversation` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ClientConversation`.
  """
  clientConversation_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ClientConversation_Data!]!
  ): [ClientConversation_KeyOutput!]! @fdc_generated(from: "ClientConversation", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ClientInboundContact` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ClientInboundContact`.
  """
  clientInboundContact_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ClientInboundContact_Data!]!
  ): [ClientInboundContact_KeyOutput!]! @fdc_generated(from: "ClientInboundContact", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PlatformAgentActivity` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformAgentActivity`.
  """
  platformAgentActivity_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PlatformAgentActivity_Data!]!
  ): [PlatformAgentActivity_KeyOutput!]! @fdc_generated(from: "PlatformAgentActivity", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PlatformChatbotConfig` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformChatbotConfig`.
  """
  platformChatbotConfig_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PlatformChatbotConfig_Data!]!
  ): [PlatformChatbotConfig_KeyOutput!]! @fdc_generated(from: "PlatformChatbotConfig", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PlatformInboundContact` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformInboundContact`.
  """
  platformInboundContact_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PlatformInboundContact_Data!]!
  ): [PlatformInboundContact_KeyOutput!]! @fdc_generated(from: "PlatformInboundContact", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PlatformOutboundContact` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformOutboundContact`.
  """
  platformOutboundContact_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PlatformOutboundContact_Data!]!
  ): [PlatformOutboundContact_KeyOutput!]! @fdc_generated(from: "PlatformOutboundContact", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PlatformOutboundOutreachEvent` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformOutboundOutreachEvent`.
  """
  platformOutboundOutreachEvent_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PlatformOutboundOutreachEvent_Data!]!
  ): [PlatformOutboundOutreachEvent_KeyOutput!]! @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PlatformOwner` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PlatformOwner`.
  """
  platformOwner_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PlatformOwner_Data!]!
  ): [PlatformOwner_KeyOutput!]! @fdc_generated(from: "PlatformOwner", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Client` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Client` or `null` if not found.
  """
  client_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Client_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Client_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Client_Data!
  ): Client_KeyOutput @fdc_generated(from: "Client", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ClientAiBotConfig` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ClientAiBotConfig` or `null` if not found.
  """
  clientAiBotConfig_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientAiBotConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientAiBotConfig_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ClientAiBotConfig_Data!
  ): ClientAiBotConfig_KeyOutput @fdc_generated(from: "ClientAiBotConfig", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ClientAiBotPerformanceEvent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ClientAiBotPerformanceEvent` or `null` if not found.
  """
  clientAiBotPerformanceEvent_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientAiBotPerformanceEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientAiBotPerformanceEvent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ClientAiBotPerformanceEvent_Data!
  ): ClientAiBotPerformanceEvent_KeyOutput @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ClientConversation` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ClientConversation` or `null` if not found.
  """
  clientConversation_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientConversation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientConversation_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ClientConversation_Data!
  ): ClientConversation_KeyOutput @fdc_generated(from: "ClientConversation", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ClientInboundContact` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ClientInboundContact` or `null` if not found.
  """
  clientInboundContact_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientInboundContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientInboundContact_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ClientInboundContact_Data!
  ): ClientInboundContact_KeyOutput @fdc_generated(from: "ClientInboundContact", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PlatformAgentActivity` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PlatformAgentActivity` or `null` if not found.
  """
  platformAgentActivity_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformAgentActivity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformAgentActivity_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PlatformAgentActivity_Data!
  ): PlatformAgentActivity_KeyOutput @fdc_generated(from: "PlatformAgentActivity", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PlatformChatbotConfig` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PlatformChatbotConfig` or `null` if not found.
  """
  platformChatbotConfig_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformChatbotConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformChatbotConfig_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PlatformChatbotConfig_Data!
  ): PlatformChatbotConfig_KeyOutput @fdc_generated(from: "PlatformChatbotConfig", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PlatformInboundContact` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PlatformInboundContact` or `null` if not found.
  """
  platformInboundContact_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformInboundContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformInboundContact_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PlatformInboundContact_Data!
  ): PlatformInboundContact_KeyOutput @fdc_generated(from: "PlatformInboundContact", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PlatformOutboundContact` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PlatformOutboundContact` or `null` if not found.
  """
  platformOutboundContact_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformOutboundContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformOutboundContact_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PlatformOutboundContact_Data!
  ): PlatformOutboundContact_KeyOutput @fdc_generated(from: "PlatformOutboundContact", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PlatformOutboundOutreachEvent` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PlatformOutboundOutreachEvent` or `null` if not found.
  """
  platformOutboundOutreachEvent_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformOutboundOutreachEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformOutboundOutreachEvent_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PlatformOutboundOutreachEvent_Data!
  ): PlatformOutboundOutreachEvent_KeyOutput @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PlatformOwner` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PlatformOwner` or `null` if not found.
  """
  platformOwner_update(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: PlatformOwner_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformOwner_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PlatformOwner_Data!
  ): PlatformOwner_KeyOutput @fdc_generated(from: "PlatformOwner", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Client` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  client_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Client_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Client_Data!
  ): Int! @fdc_generated(from: "Client", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ClientAiBotConfig` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  clientAiBotConfig_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ClientAiBotConfig_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ClientAiBotConfig_Data!
  ): Int! @fdc_generated(from: "ClientAiBotConfig", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ClientAiBotPerformanceEvent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  clientAiBotPerformanceEvent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ClientAiBotPerformanceEvent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ClientAiBotPerformanceEvent_Data!
  ): Int! @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ClientConversation` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  clientConversation_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ClientConversation_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ClientConversation_Data!
  ): Int! @fdc_generated(from: "ClientConversation", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ClientInboundContact` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  clientInboundContact_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ClientInboundContact_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ClientInboundContact_Data!
  ): Int! @fdc_generated(from: "ClientInboundContact", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PlatformAgentActivity` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  platformAgentActivity_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PlatformAgentActivity_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PlatformAgentActivity_Data!
  ): Int! @fdc_generated(from: "PlatformAgentActivity", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PlatformChatbotConfig` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  platformChatbotConfig_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PlatformChatbotConfig_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PlatformChatbotConfig_Data!
  ): Int! @fdc_generated(from: "PlatformChatbotConfig", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PlatformInboundContact` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  platformInboundContact_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PlatformInboundContact_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PlatformInboundContact_Data!
  ): Int! @fdc_generated(from: "PlatformInboundContact", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PlatformOutboundContact` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  platformOutboundContact_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PlatformOutboundContact_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PlatformOutboundContact_Data!
  ): Int! @fdc_generated(from: "PlatformOutboundContact", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PlatformOutboundOutreachEvent` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  platformOutboundOutreachEvent_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PlatformOutboundOutreachEvent_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PlatformOutboundOutreachEvent_Data!
  ): Int! @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PlatformOwner` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  platformOwner_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PlatformOwner_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PlatformOwner_Data!
  ): Int! @fdc_generated(from: "PlatformOwner", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Client` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  client_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Client_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Client_FirstRow
  ): Client_KeyOutput @fdc_generated(from: "Client", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ClientAiBotConfig` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  clientAiBotConfig_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientAiBotConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientAiBotConfig_FirstRow
  ): ClientAiBotConfig_KeyOutput @fdc_generated(from: "ClientAiBotConfig", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ClientAiBotPerformanceEvent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  clientAiBotPerformanceEvent_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientAiBotPerformanceEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientAiBotPerformanceEvent_FirstRow
  ): ClientAiBotPerformanceEvent_KeyOutput @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ClientConversation` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  clientConversation_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientConversation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientConversation_FirstRow
  ): ClientConversation_KeyOutput @fdc_generated(from: "ClientConversation", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ClientInboundContact` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  clientInboundContact_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientInboundContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientInboundContact_FirstRow
  ): ClientInboundContact_KeyOutput @fdc_generated(from: "ClientInboundContact", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PlatformAgentActivity` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  platformAgentActivity_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformAgentActivity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformAgentActivity_FirstRow
  ): PlatformAgentActivity_KeyOutput @fdc_generated(from: "PlatformAgentActivity", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PlatformChatbotConfig` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  platformChatbotConfig_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformChatbotConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformChatbotConfig_FirstRow
  ): PlatformChatbotConfig_KeyOutput @fdc_generated(from: "PlatformChatbotConfig", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PlatformInboundContact` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  platformInboundContact_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformInboundContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformInboundContact_FirstRow
  ): PlatformInboundContact_KeyOutput @fdc_generated(from: "PlatformInboundContact", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PlatformOutboundContact` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  platformOutboundContact_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformOutboundContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformOutboundContact_FirstRow
  ): PlatformOutboundContact_KeyOutput @fdc_generated(from: "PlatformOutboundContact", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PlatformOutboundOutreachEvent` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  platformOutboundOutreachEvent_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformOutboundOutreachEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformOutboundOutreachEvent_FirstRow
  ): PlatformOutboundOutreachEvent_KeyOutput @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PlatformOwner` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  platformOwner_delete(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: PlatformOwner_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformOwner_FirstRow
  ): PlatformOwner_KeyOutput @fdc_generated(from: "PlatformOwner", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Client` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  client_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Client_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Client", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ClientAiBotConfig` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  clientAiBotConfig_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ClientAiBotConfig_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ClientAiBotConfig", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ClientAiBotPerformanceEvent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  clientAiBotPerformanceEvent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ClientAiBotPerformanceEvent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ClientConversation` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  clientConversation_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ClientConversation_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ClientConversation", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ClientInboundContact` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  clientInboundContact_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ClientInboundContact_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ClientInboundContact", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PlatformAgentActivity` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  platformAgentActivity_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PlatformAgentActivity_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PlatformAgentActivity", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PlatformChatbotConfig` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  platformChatbotConfig_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PlatformChatbotConfig_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PlatformChatbotConfig", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PlatformInboundContact` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  platformInboundContact_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PlatformInboundContact_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PlatformInboundContact", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PlatformOutboundContact` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  platformOutboundContact_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PlatformOutboundContact_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PlatformOutboundContact", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PlatformOutboundOutreachEvent` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  platformOutboundOutreachEvent_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PlatformOutboundOutreachEvent_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PlatformOwner` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  platformOwner_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PlatformOwner_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PlatformOwner", purpose: DELETE_MULTIPLE)
}
