extend type Query {
  """
  ✨ Look up a single `Client` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  client(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Client_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Client_FirstRow
  ): Client @fdc_generated(from: "Client", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ClientAiBotConfig` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  clientAiBotConfig(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientAiBotConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientAiBotConfig_FirstRow
  ): ClientAiBotConfig @fdc_generated(from: "ClientAiBotConfig", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ClientAiBotPerformanceEvent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  clientAiBotPerformanceEvent(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientAiBotPerformanceEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientAiBotPerformanceEvent_FirstRow
  ): ClientAiBotPerformanceEvent @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ClientConversation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  clientConversation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientConversation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientConversation_FirstRow
  ): ClientConversation @fdc_generated(from: "ClientConversation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ClientInboundContact` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  clientInboundContact(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ClientInboundContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ClientInboundContact_FirstRow
  ): ClientInboundContact @fdc_generated(from: "ClientInboundContact", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PlatformAgentActivity` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  platformAgentActivity(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformAgentActivity_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformAgentActivity_FirstRow
  ): PlatformAgentActivity @fdc_generated(from: "PlatformAgentActivity", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PlatformChatbotConfig` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  platformChatbotConfig(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformChatbotConfig_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformChatbotConfig_FirstRow
  ): PlatformChatbotConfig @fdc_generated(from: "PlatformChatbotConfig", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PlatformInboundContact` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  platformInboundContact(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformInboundContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformInboundContact_FirstRow
  ): PlatformInboundContact @fdc_generated(from: "PlatformInboundContact", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PlatformOutboundContact` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  platformOutboundContact(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformOutboundContact_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformOutboundContact_FirstRow
  ): PlatformOutboundContact @fdc_generated(from: "PlatformOutboundContact", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PlatformOutboundOutreachEvent` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  platformOutboundOutreachEvent(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PlatformOutboundOutreachEvent_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformOutboundOutreachEvent_FirstRow
  ): PlatformOutboundOutreachEvent @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PlatformOwner` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  platformOwner(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: PlatformOwner_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PlatformOwner_FirstRow
  ): PlatformOwner @fdc_generated(from: "PlatformOwner", purpose: QUERY_SINGLE)
  """
  ✨ List `Client` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  clients(
    """
    Filter condition to narrow down the query results.
    """
    where: Client_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Client_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Client_Having
  ): [Client!]! @fdc_generated(from: "Client", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ClientAiBotConfig` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  clientAiBotConfigs(
    """
    Filter condition to narrow down the query results.
    """
    where: ClientAiBotConfig_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ClientAiBotConfig_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ClientAiBotConfig_Having
  ): [ClientAiBotConfig!]! @fdc_generated(from: "ClientAiBotConfig", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ClientAiBotPerformanceEvent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  clientAiBotPerformanceEvents(
    """
    Filter condition to narrow down the query results.
    """
    where: ClientAiBotPerformanceEvent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ClientAiBotPerformanceEvent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ClientAiBotPerformanceEvent_Having
  ): [ClientAiBotPerformanceEvent!]! @fdc_generated(from: "ClientAiBotPerformanceEvent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ClientConversation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  clientConversations(
    """
    Filter condition to narrow down the query results.
    """
    where: ClientConversation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ClientConversation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ClientConversation_Having
  ): [ClientConversation!]! @fdc_generated(from: "ClientConversation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ClientInboundContact` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  clientInboundContacts(
    """
    Filter condition to narrow down the query results.
    """
    where: ClientInboundContact_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ClientInboundContact_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ClientInboundContact_Having
  ): [ClientInboundContact!]! @fdc_generated(from: "ClientInboundContact", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PlatformAgentActivity` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  platformAgentActivities(
    """
    Filter condition to narrow down the query results.
    """
    where: PlatformAgentActivity_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlatformAgentActivity_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlatformAgentActivity_Having
  ): [PlatformAgentActivity!]! @fdc_generated(from: "PlatformAgentActivity", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PlatformChatbotConfig` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  platformChatbotConfigs(
    """
    Filter condition to narrow down the query results.
    """
    where: PlatformChatbotConfig_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlatformChatbotConfig_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlatformChatbotConfig_Having
  ): [PlatformChatbotConfig!]! @fdc_generated(from: "PlatformChatbotConfig", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PlatformInboundContact` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  platformInboundContacts(
    """
    Filter condition to narrow down the query results.
    """
    where: PlatformInboundContact_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlatformInboundContact_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlatformInboundContact_Having
  ): [PlatformInboundContact!]! @fdc_generated(from: "PlatformInboundContact", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PlatformOutboundContact` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  platformOutboundContacts(
    """
    Filter condition to narrow down the query results.
    """
    where: PlatformOutboundContact_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlatformOutboundContact_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlatformOutboundContact_Having
  ): [PlatformOutboundContact!]! @fdc_generated(from: "PlatformOutboundContact", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PlatformOutboundOutreachEvent` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  platformOutboundOutreachEvents(
    """
    Filter condition to narrow down the query results.
    """
    where: PlatformOutboundOutreachEvent_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlatformOutboundOutreachEvent_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlatformOutboundOutreachEvent_Having
  ): [PlatformOutboundOutreachEvent!]! @fdc_generated(from: "PlatformOutboundOutreachEvent", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PlatformOwner` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  platformOwners(
    """
    Filter condition to narrow down the query results.
    """
    where: PlatformOwner_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PlatformOwner_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PlatformOwner_Having
  ): [PlatformOwner!]! @fdc_generated(from: "PlatformOwner", purpose: QUERY_MULTIPLE)
}
